include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    avoid_print: ignore
    avoid_types_as_parameter_names: ignore
    deprecated_member_use: ignore
    unused_element: ignore
    use_build_context_synchronously: ignore
