name: be_project_campus_connect
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  cloud_firestore: ^5.6.5
  device_info_plus: ^11.3.0
  excel: ^4.0.6
  file_picker: ^9.0.2
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  google_fonts: ^6.2.1
  intl: ^0.20.2
  lottie: ^3.3.0
  open_file: ^3.5.10
  path_provider: ^2.1.5
  pdf: ^3.11.3
  permission_handler: ^11.4.0
  printing: ^5.14.2
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
